<div id="ft-content"><div><div class="wrapper">
<p class="clearfix">
<span class="copyright">&copy; <%=Year(Date)%>&nbsp;<%=globals("COMPANY")%></span>
<span class="footer-links"><a href="<%=globals("SITEURL")%>/legal/privacy.asp" title="Our Privacy Policy">Privacy Policy</a> | <a href="<%=globals("SITEURL")%>/legal/terms.asp" title="Our Terms of Use">Terms of Use</a></span>
<span class="shameless-plug">Powered by <%=globals("DEVELOPER_LINK")%></span>
</p>
</div></div></div>

