<title><%=page.getTitle()%></title>
<meta http-equiv="Content-Type" content="text/html; charset=<%=page.getCharEncoding()%>" />
<meta name="description" content="<%=page.getDescription()%>" />
<meta name="keywords" content="<%=page.getKeywords()%>" />
<meta name="copyright" content="Copyright <%=Year(Date())&" "&globals("COMPANY")%>"/>
<meta name="copyright" content="SITE DESIGN Copyright <%=Year(Date())&" "&globals("DEVELOPER_NAME")%>"/>
<meta name="author" content="<%=globals("DEVELOPER_NAME")%>"/>
<meta name="author" content="James Wilson"/>
<meta name="ROBOTS" content="INDEX, FOLLOW"/>
<meta name="robots" content="All"/>
<meta name="revisit-after" content="1 days"/>
<meta name="rating" content="GENERAL"/>
<meta name="distribution" content="Global"/>
<meta name="resource-type" content="document"/>
<meta http-equiv="imagetoolbar" content="no"/>
<meta http-equiv="content-language" content="en-us"/>
<meta http-equiv="content-style-type" content="text/css"/>
<meta http-equiv="content-script-type" content="text/javascript"/>
<link rel="shortcut icon" href="<%=globals("FAVICON")%>"/>
