<div id="ft-content"><div><div class="wrapper">
<p class="clearfix">
<span class="copyright">&copy; <%=Year(Date)%>&nbsp;<%=objLinks("COMPANY")%></span>
<span class="footer-links"><a href="<%=objLinks("SITEURL")%>/legal/privacy.asp" title="Our Privacy Policy">Privacy Policy</a> | <a href="<%=objLinks("SITEURL")%>/legal/terms.asp" title="Our Terms of Use">Terms of Use</a></span>
<span class="shameless-plug">Site by <%=objLinks("PROVIDER_LINK")%></span>
</p>
</div></div></div>

